# Generated by Django 4.2.8 on 2023-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Israel', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='ohad@ohad.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(default='Nadav Storfer', max_length=255),
        ),
    ]
