# Generated by Django 4.2.8 on 2023-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_photographer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censoredimg',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sessionalbum',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
