# Generated by Django 4.2.8 on 2023-12-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_personalalbum_photographer_personalalbum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalalbum',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
