# Generated by Django 4.2.6 on 2023-12-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_personalalbum_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='personal_album',
        ),
        migrations.AddField(
            model_name='img',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalalbum',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.img')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='base.order')),
                ('personal_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.personalalbum')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, to='base.message')),
                ('participants', models.ManyToManyField(related_name='user_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singlePhotoPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_1_to_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6_to_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_11_to_20', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_21_to_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_51_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='user_chats', to='base.chat'),
        ),
        migrations.AddField(
            model_name='sessionalbum',
            name='albums_prices',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.albumsprices'),
        ),
    ]
