# Generated by Django 4.2.8 on 2024-01-01 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_personalalbum_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='sessDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
