# Generated by Django 4.2.8 on 2024-01-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_sessionalbum_sessdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.CharField(default='Tel Aviv', max_length=20),
        ),
        migrations.AddField(
            model_name='spot',
            name='country',
            field=models.CharField(default='Israel', max_length=20),
        ),
    ]
