# Generated by Django 4.2.8 on 2024-01-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_spot_city_spot_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
