# Generated by Django 4.2.8 on 2024-01-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.URLField(blank=True, default='default.png', null=True),
        ),
    ]
