# Generated by Django 4.2.8 on 2024-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_photographer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.CharField(blank=True, default='default.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.CharField(blank=True, default='default.png', max_length=255, null=True),
        ),
    ]
