# Generated by Django 4.2.8 on 2024-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_spot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
