# Generated by Django 4.2.8 on 2024-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_spot_city_alter_spot_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalbum',
            name='sessDate',
            field=models.DateTimeField(),
        ),
    ]
