# Generated by Django 4.2.8 on 2024-01-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_sessionalbum_sessdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalbum',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
