# Generated by Django 4.2.8 on 2024-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_sessionalbum_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalbum',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
