# Generated by Django 4.2.8 on 2024-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_sessionalbum_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalalbum',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
