# Generated by Django 4.2.8 on 2024-01-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_img_photo_alter_personalalbum_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalalbum',
            name='user',
        ),
    ]
