# Generated by Django 4.2.8 on 2024-01-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_img_price_alter_personalalbum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
