# Generated by Django 4.2.8 on 2024-05-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_img_personal_album_alter_img_wave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censoredimg',
            name='img',
        ),
        migrations.RemoveField(
            model_name='censoredimg',
            name='personal_album',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='img',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='personal_album',
        ),
        migrations.RemoveField(
            model_name='personalalbum',
            name='session_album',
        ),
        migrations.RemoveField(
            model_name='sessionalbum',
            name='albums_prices',
        ),
        migrations.DeleteModel(
            name='AlbumsPrices',
        ),
        migrations.DeleteModel(
            name='CensoredImg',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PersonalAlbum',
        ),
    ]
