# Generated by Django 4.2.8 on 2024-05-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_img_watermarkedphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singlePhotoPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_1_to_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6_to_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_11_to_20', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_21_to_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_51_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum')),
            ],
        ),
    ]
