# Generated by Django 4.2.8 on 2024-06-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumsprices',
            old_name='price_11_to_20',
            new_name='price_6_to_20',
        ),
        migrations.RemoveField(
            model_name='albumsprices',
            name='price_6_to_10',
        ),
        migrations.RemoveField(
            model_name='albumsprices',
            name='singlePhotoPrice',
        ),
    ]
