# Generated by Django 4.2.8 on 2024-06-23 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_price_11_to_20_albumsprices_price_6_to_20_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='surfer',
        ),
        migrations.AddField(
            model_name='order',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.photographer'),
        ),
    ]
