# Generated by Django 4.2.8 on 2024-06-23 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_purchaseitem_rename_order_purchase_delete_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_photographer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='surfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_surfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
