# Generated by Django 4.2.8 on 2024-06-23 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_purchase_photographer_alter_purchase_surfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_img_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.img'),
        ),
    ]
