# Generated by Django 4.2.8 on 2024-06-24 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_purchase_total_img_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_img_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='Wave',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='img_quantity',
        ),
        migrations.AddField(
            model_name='img',
            name='SessionAlbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_item_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='Img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Img', to='base.img'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='SessionAlbum',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='item_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='wave',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wave'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('WatermarkedVideo', models.CharField(blank=True, max_length=255, null=True)),
                ('SessionAlbum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='Video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Video', to='base.video'),
        ),
    ]
