# Generated by Django 4.2.8 on 2024-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_purchase_total_img_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='videos',
            field=models.BooleanField(default=False),
        ),
    ]
