# Generated by Django 4.2.8 on 2024-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_sessionalbum_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
