# Generated by Django 4.2.8 on 2024-07-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_video_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsPricesForVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1_to_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6_to_15', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_16_to_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sessionalbum')),
            ],
        ),
    ]
