# Generated by Django 4.2.8 on 2024-07-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_albumspricesforvideos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumspricesforvideos',
            old_name='price_16_to_plus',
            new_name='price_16_plus',
        ),
    ]
