# Generated by Django 4.2.8 on 2024-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_price_16_to_plus_albumspricesforvideos_price_16_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='dividedToWaves',
            field=models.BooleanField(default=False),
        ),
    ]
