# Generated by Django 4.2.8 on 2024-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_sessionalbum_dividedtowaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='price',
        ),
    ]
