# Generated by Django 4.2.8 on 2024-07-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_img_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wave'),
        ),
        migrations.AlterField(
            model_name='sessionalbum',
            name='dividedToWaves',
            field=models.BooleanField(null=True),
        ),
    ]
