# Generated by Django 4.2.8 on 2024-08-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_purchaseitem_sessionalbum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_photographer', to='base.photographer'),
        ),
    ]
