# Generated by Django 4.2.8 on 2024-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_purchase_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
