# Generated by Django 4.2.8 on 2024-08-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_sessionalbum_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalbum',
            name='dividedToWaves',
            field=models.BooleanField(default=False),
        ),
    ]
