# Generated by Django 4.2.8 on 2024-08-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_sessionalbum_dividedtowaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sessDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='spot_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
