# Generated by Django 4.2.8 on 2024-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_purchase_sessdate_purchase_spot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='photographer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='surfer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
