# Generated by Django 4.2.8 on 2024-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_purchase_photographer_name_purchase_surfer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
