# Generated by Django 4.2.8 on 2024-10-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_sessionalbum_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAlbumsPricesForVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1_to_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6_to_15', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_16_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAlbumsPricesForImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1_to_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6_to_20', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_21_to_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_51_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.photographer')),
            ],
        ),
    ]
