# Generated by Django 4.2.8 on 2024-10-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_defaultalbumspricesforvideos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumsprices',
            old_name='price_21_to_50',
            new_name='price_6_to_50',
        ),
        migrations.RenameField(
            model_name='albumspricesforvideos',
            old_name='price_1_to_5',
            new_name='price_1_to_3',
        ),
        migrations.RenameField(
            model_name='albumspricesforvideos',
            old_name='price_6_to_15',
            new_name='price_4_to_15',
        ),
        migrations.RemoveField(
            model_name='albumsprices',
            name='price_6_to_20',
        ),
    ]
