# Generated by Django 4.2.8 on 2024-10-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_rename_price_21_to_50_albumsprices_price_6_to_50_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultalbumspricesforimages',
            old_name='price_21_to_50',
            new_name='price_6_to_50',
        ),
        migrations.RenameField(
            model_name='defaultalbumspricesforvideos',
            old_name='price_1_to_5',
            new_name='price_1_to_3',
        ),
        migrations.RenameField(
            model_name='defaultalbumspricesforvideos',
            old_name='price_6_to_15',
            new_name='price_4_to_15',
        ),
        migrations.RemoveField(
            model_name='defaultalbumspricesforimages',
            name='price_6_to_20',
        ),
    ]
