# Generated by Django 4.2.8 on 2024-10-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_rename_price_21_to_50_defaultalbumspricesforimages_price_6_to_50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsprices',
            name='price_1_to_5',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albumsprices',
            name='price_51_plus',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albumsprices',
            name='price_6_to_50',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albumspricesforvideos',
            name='price_16_plus',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albumspricesforvideos',
            name='price_1_to_3',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albumspricesforvideos',
            name='price_4_to_15',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_1_to_5',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_51_plus',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_6_to_50',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_16_plus',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_1_to_3',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_4_to_15',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
