# Generated by Django 4.2.8 on 2024-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_customuser_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
