# Generated by Django 4.2.8 on 2024-11-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_photographer_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_1_to_5',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_51_plus',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforimages',
            name='price_6_to_50',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_16_plus',
            field=models.DecimalField(decimal_places=1, default=35.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_1_to_3',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultalbumspricesforvideos',
            name='price_4_to_15',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=10),
        ),
    ]
