# Generated by Django 4.2.8 on 2024-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_video_wave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='videosPerAlbums',
            field=models.BooleanField(default=False),
        ),
    ]
