# Generated by Django 4.2.8 on 2024-12-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_sessionalbum_videosperalbums'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='filenames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='zipFileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
