# Generated by Django 4.2.8 on 2024-12-23 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_purchase_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='surfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_surfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
