# Generated by Django 4.2.8 on 2025-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_purchase_surfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
