# Generated by Django 4.2.8 on 2025-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_purchase_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='netPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
