# Generated by Django 4.2.8 on 2025-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_purchase_netprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalbum',
            name='forever',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
