# Generated by Django 4.2.8 on 2025-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_sessionalbum_forever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalbum',
            name='forever',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
